local text = "ควย, หี, pussy, i love kid, i love you, fuck you, cock, shit, nigger, fuck roblox love kid, pedro"

while task.wait(0.25) do
	print(text)
	print("https://xn--72c6c2a3an.com/tag/clip2vip/")
	print(text)
	print("https://xn--72c6c2a3an.com/tag/clip2vip/")
	print(text)
	print("https://xn--72c6c2a3an.com/tag/clip2vip/")
	print(text)
	print("https://xn--72c6c2a3an.com/tag/clip2vip/")
	print(text)
	print("https://xn--72c6c2a3an.com/tag/clip2vip/")
	print(text)
	print("https://xn--72c6c2a3an.com/tag/clip2vip/")
	print(text)
	print("https://xn--72c6c2a3an.com/tag/clip2vip/")
	print(text)
	print("https://xn--72c6c2a3an.com/tag/clip2vip/")
	print(text)
	print("https://xn--72c6c2a3an.com/tag/clip2vip/")
	print(text)
	print("https://xn--72c6c2a3an.com/tag/clip2vip/")
	print(text)
	print("https://xn--72c6c2a3an.com/tag/clip2vip/")
	print(text)
	print("https://xn--72c6c2a3an.com/tag/clip2vip/")
	print(text)
	print("https://xn--72c6c2a3an.com/tag/clip2vip/")
	print(text)
	print("https://xn--72c6c2a3an.com/tag/clip2vip/")
	print(text)
	print("https://xn--72c6c2a3an.com/tag/clip2vip/")
	print(text)
	print("https://xn--72c6c2a3an.com/tag/clip2vip/")
	print(text)
	print("https://xn--72c6c2a3an.com/tag/clip2vip/")
	print(text)
	print("https://xn--72c6c2a3an.com/tag/clip2vip/")
	print(text)
	print("https://xn--72c6c2a3an.com/tag/clip2vip/")
	print(text)
	print("https://xn--72c6c2a3an.com/tag/clip2vip/")
	print(text)
	print("https://xn--72c6c2a3an.com/tag/clip2vip/")

	print(text)
	print("https://xn--72c6c2a3an.com/tag/clip2vip/")
	print(text)
	print("https://xn--72c6c2a3an.com/tag/clip2vip/")
	print(text)
	print("https://xn--72c6c2a3an.com/tag/clip2vip/")
	print(text)
	print("https://xn--72c6c2a3an.com/tag/clip2vip/")
	print(text)
	print("https://xn--72c6c2a3an.com/tag/clip2vip/")	print(text)
	print("https://xn--72c6c2a3an.com/tag/clip2vip/")
	print(text)
	print("https://xn--72c6c2a3an.com/tag/clip2vip/")
	print(text)
	print("https://xn--72c6c2a3an.com/tag/clip2vip/")
	print(text)
	print("https://xn--72c6c2a3an.com/tag/clip2vip/")
	print(text)
	print("https://xn--72c6c2a3an.com/tag/clip2vip/")
	print(text)
	print("https://xn--72c6c2a3an.com/tag/clip2vip/")

	print(text)
	print("https://xn--72c6c2a3an.com/tag/clip2vip/")	print(text)
	print("https://xn--72c6c2a3an.com/tag/clip2vip/")
	print(text)
	print("https://xn--72c6c2a3an.com/tag/clip2vip/")
	print(text)
	print("https://xn--72c6c2a3an.com/tag/clip2vip/")
	print(text)
	print("https://xn--72c6c2a3an.com/tag/clip2vip/")
	print(text)
	print("https://xn--72c6c2a3an.com/tag/clip2vip/")

	print(text)
	print("https://xn--72c6c2a3an.com/tag/clip2vip/")	print(text)
	print("https://xn--72c6c2a3an.com/tag/clip2vip/")
	print(text)
	print("https://xn--72c6c2a3an.com/tag/clip2vip/")
	print(text)
	print("https://xn--72c6c2a3an.com/tag/clip2vip/")
	print(text)
	print("https://xn--72c6c2a3an.com/tag/clip2vip/")

	print(text)
	print("https://xn--72c6c2a3an.com/tag/clip2vip/")
	print(text)
	print("https://xn--72c6c2a3an.com/tag/clip2vip/")	print(text)
	print("https://xn--72c6c2a3an.com/tag/clip2vip/")
	print(text)
	print("https://xn--72c6c2a3an.com/tag/clip2vip/")
	print(text)
	print("https://xn--72c6c2a3an.com/tag/clip2vip/")
	print(text)
	print("https://xn--72c6c2a3an.com/tag/clip2vip/")

end
